# Generated by Django 6.0 on 2026-01-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='reservation.cinema', verbose_name='سینما')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='فیلم')),
            ],
            options={
                'verbose_name': 'اکران',
                'verbose_name_plural': 'اکران\u200cها',
                'unique_together': {('movie', 'cinema', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1, verbose_name='ردیف')),
                ('number', models.IntegerField(verbose_name='شماره صندلی')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='رزرو شده؟')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='screenings.screening', verbose_name='اکران')),
            ],
            options={
                'verbose_name': 'صندلی',
                'verbose_name_plural': 'صندلی\u200cها',
                'unique_together': {('screening', 'row', 'number')},
            },
        ),
    ]
