# Generated by Django 6.0 on 2026-01-21 15:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_unique_together_and_more'),
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screening',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={},
        ),
        migrations.AddField(
            model_name='screening',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 15, 2, 21, 786500, tzinfo=datetime.timezone.utc), verbose_name='زمان پایان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screening',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='reservation.cinema', verbose_name='نام سینما'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='seat',
            name='screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='screenings.screening'),
        ),
    ]
