# Generated by Django 6.0 on 2026-02-09 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_remove_cinema_address_cinema_city_and_more'),
        ('screenings', '0002_alter_screening_options_alter_seat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screening',
            options={'verbose_name': 'اکران', 'verbose_name_plural': 'اکران\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['row', 'number'], 'verbose_name': 'صندلی', 'verbose_name_plural': 'صندلی\u200cها'},
        ),
        migrations.AlterField(
            model_name='screening',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.cinema', verbose_name='سینما'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_reserved',
            field=models.BooleanField(default=False, verbose_name='رزرو شده'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.PositiveIntegerField(verbose_name='شماره صندلی'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(max_length=5, verbose_name='ردیف'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='screenings.screening', verbose_name='اکران'),
        ),
    ]
