# Generated by Django 6.0 on 2026-02-11 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_actors_movie_director_alter_movie_genre'),
        ('reservation', '0008_alter_cinema_options_alter_reservation_options_and_more'),
        ('screenings', '0003_alter_screening_options_alter_seat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screening',
            options={'ordering': ['start_time'], 'verbose_name': 'برنامه اکران', 'verbose_name_plural': 'برنامه\u200cهای اکران'},
        ),
        migrations.RemoveField(
            model_name='screening',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='price',
        ),
        migrations.AddField(
            model_name='screening',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=100, verbose_name='ظرفیت سانس'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screening',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='reservation.cinema', verbose_name='سینما'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='movies.movie', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='start_time',
            field=models.DateTimeField(verbose_name='زمان شروع سانس'),
        ),
    ]
