# Generated by Django 6.0 on 2026-02-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='موجودی کیف پول'),
        ),
    ]
