# Generated by Django 6.0 on 2026-01-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سینما')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'تایید شده'), ('CANCELLED', 'لغو شده'), ('PENDING', 'در انتظار پرداخت')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('tracking_code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
            ],
        ),
    ]
