# Generated by Django 6.0 on 2026-01-21 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_initial'),
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='capacity',
            field=models.PositiveIntegerField(default=50, verbose_name='ظرفیت سالن'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='screenings.seat', verbose_name='صندلی'),
        ),
    ]
