# Generated by Django 6.0 on 2026-02-02 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_unique_together_and_more'),
        ('screenings', '0002_alter_screening_options_alter_seat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenings.seat', verbose_name='صندلی'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'تایید شده'), ('CANCELLED', 'لغو شده'), ('PENDING', 'در انتظار پرداخت')], default='PENDING', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tracking_code',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
