# Generated by Django 6.0 on 2026-02-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_seat_alter_reservation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='tracking_code',
            field=models.CharField(default='TEMP000000', editable=False, max_length=12, unique=True, verbose_name='کد پیگیری'),
            preserve_default=False,
        ),
    ]
