# Generated by Django 6.0 on 2026-02-09 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_tracking_code'),
        ('screenings', '0002_alter_screening_options_alter_seat_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='address',
        ),
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='screenings.seat', verbose_name='صندلی'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('CONFIRMED', 'قطعی شده'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
