# Generated by Django 6.0 on 2026-02-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_remove_cinema_address_cinema_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='رزرو تا'),
        ),
    ]
