# Generated by Django 6.0 on 2026-02-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_reservation_reserved_until'),
        ('screenings', '0003_alter_screening_options_alter_seat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={'verbose_name': 'سینما', 'verbose_name_plural': 'سینماها'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'رزرو', 'verbose_name_plural': 'رزروها'},
        ),
        migrations.AddField(
            model_name='cinema',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='capacity',
            field=models.PositiveIntegerField(default=100, verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام سینما'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_until',
            field=models.DateTimeField(blank=True, help_text='اگر وضعیت PENDING است تا چه زمانی رزرو قفل باشد', null=True, verbose_name='رزرو تا زمان'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenings.screening', verbose_name='سانس/اکران'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('CONFIRMED', 'قطعی'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
