# Generated by Django 6.0 on 2026-01-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فیلم')),
                ('description', models.TextField(verbose_name='توضیحات فیلم')),
                ('release_date', models.DateField(verbose_name='تاریخ اکران')),
                ('duration', models.DurationField(verbose_name='مدت زمان')),
                ('poster_image', models.ImageField(upload_to='movies/', verbose_name='تصویر پوستر')),
            ],
        ),
    ]
