# Generated by Django 6.0 on 2026-02-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'اکشن'), ('drama', 'درام'), ('comedy', 'کمدی'), ('scifi', 'علمی تخیلی'), ('horror', 'ترسناک'), ('documentary', 'مستند')], default='drama', max_length=50, verbose_name='ژانر'),
        ),
    ]
