# Generated by Django 6.0 on 2026-02-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(default='نامشخص', help_text='نام بازیگران را با ویرگول جدا کنید', max_length=500, verbose_name='بازیگران اصلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='نامشخص', max_length=100, verbose_name='کارگردان'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'اکشن'), ('comedy', 'کمدی'), ('drama', 'درام'), ('sci-fi', 'علمی تخیلی'), ('horror', 'وحشت'), ('animation', 'انیمیشن'), ('documentary', 'مستند')], default='drama', max_length=50, verbose_name='ژانر'),
        ),
    ]
